### ISSUE TITLE
Forever issue when trying to start

### ISSUE THREAD

**Issue by SavageTheUnicorn** [rossimo/retrobot#11]
I do not know how to format this or explain everything as easily as possible. 
![Screenshot_20220918-052044](https://user-images.githubusercontent.com/57853203/190897460-7fadeb5c-8bed-487a-b410-abc7eba940de.png)
![Screenshot_20220918-043432](https://user-images.githubusercontent.com/57853203/190897461-90997cfc-a125-48ab-a180-d821827e5154.png)
#
I am working on uploading the retrobot.log from the forever folder.

**Comment by SavageTheUnicorn** [comment]
[retrobot.log](https://github.com/rossimo/retrobot/files/9593757/retrobot.log)

**Comment by rossimo** [comment]
You mentioned earlier that running the command with `sudo` seemed to fix the problem. That sounds like a `$PATH` problem maybe? I would run a `which forever` as normal user, and as root to get a clue to what may be happening.

Also, you shouldn't need to manually run `forever` yourself. The `yarn service:start` should automatically find the `forever` script in `node_modules`. Maybe you've run `yarn install` as root by mistake, causing permission issues?

After looking at the `retrobot.log`, I'm wanting to think that there was a problem with the token that was eventually resolved.

**Comment by SavageTheUnicorn** [comment]
> After looking at the `retrobot.log`, I'm wanting to think that there was a problem with the token that was eventually resolved.

Yes, but the bot still remains offline and the same error is received.

> Also, you shouldn't need to manually run forever yourself. The yarn service:start should automatically find the forever script in node_modules. Maybe you've run yarn install as root by mistake, causing permission issues?

No, I hadn't ran anything as root I was only adding sudo to the beginning of the command when I got output back.

> You mentioned earlier that running the command with sudo seemed to fix the problem. That sounds like a $PATH problem maybe? I would run a which forever as normal user, and as root to get a clue to what may be happening.

Outputs /usr/local/bin/forever when run either way. Root obtained via sudo su.

**Comment by rossimo** [comment]
Ok, the second screenshot is expected output. The bot will become a daemon at that point, and continue to run in the background are initializing for a couple seconds. If the console output of `yarn start` and the `forever` log are the same, then we can rule out this is a issue with running the bot in service mode. Can you confirm that?

**Comment by SavageTheUnicorn** [comment]
> Ok, the second screenshot is expected output. The bot will become a daemon at that point, and continue to run in the background are initializing for a couple seconds. If the console output of `yarn start` and the `forever` log are the same, then we can rule out this is a issue with running the bot in service mode. Can you confirm that?

Ah sorry.. How is that done? I'm a bit of a beginner with Linux in general.

**Comment by rossimo** [comment]
Forgot to add this step to the docs. Be sure "Message Content Intent" is enabled in the Discord Developer Portal.
![Screenshot 2022-09-18 143012](https://user-images.githubusercontent.com/719699/190923015-ddbce9e7-a7c5-46a4-b081-160e55328b2a.png)
