### ISSUE TITLE
Wrong volume path in docker-compose.yml.example ?

### ISSUE THREAD

**Issue by sedand** [rossimo/retrobot#17]
Not 100% sure - but shouldn't line 5 in `docker-compose.yml.example` be:
`      - ./data:/retrobot/data`
instead of
`      - ./data:/srv/data`
?

as the Dockerfile contains: `WORKDIR /retrobot`

P.S.: Thanks for this really cool discord toy! :)

**Comment by rossimo** [comment]
@zikes Does this look good to you?

**Comment by zikes** [comment]
Ah yes, the game data is stored at `/retrobot/data` in Docker.
