### ISSUE TITLE
(feat request) official docker image

### ISSUE THREAD

**Issue by Xstar97** [rossimo/retrobot#20]
Are you willing to create docker images on docker hub officially?

this appears to be a clone -> https://hub.docker.com/r/aronjanosch/retrobot

**Comment by silasary** [comment]
I have a github workflow to make images on the Github Container Registry.  I can PR it if you want

**Comment by rossimo** [comment]
https://hub.docker.com/r/rossimo/retrobot and http://ghcr.io/rossimo/retrobot now exist. Need to finish out the README, and should be able to close this.

What command do you normally run to fire up your container, @silasary ?

**Comment by silasary** [comment]
A basic command would be one of: 

* `docker run -d -v ./data:/retrobot/data -e DISCORD_TOKEN=XXXXX rossimo/retrobot`
* `docker run -d -v ./data:/retrobot/data --envfile .env rossimo/retrobot`

**Comment by rossimo** [comment]
Done, thanks @silasary
